### ISSUE TITLE
Override delete() instead of adding softDelete()

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-softdelete#1]
It would be better, to override the actual delete() method, instead of having to rely on replacing all occurences of delete() with softDelete();

forceDelete is already in place to handle the hard deletions.

**Comment by lekoala** [comment]
it's a good idea, but I'm not sure how to do it with a DataExtension. Using onBeforeDelete is not a good fit (no way to prevent the delete, and I need to make sure all hooks are properly called). Also, other modules may rely on the delete function to really delete the DataObject, which could lead to side effects.

So currently, the safest way to do this is to have a separate method. But I'm open to any clear plan to make the soft delete behaviour more developer friendly :-)

**Comment by lekoala** [comment]
i'm closing this :) feel free to reopen if need be
