### ISSUE TITLE
Soft delete with relation filter fails

### ISSUE THREAD

**Issue by rasstislav** [lekoala/silverstripe-softdelete#7]
Hello,

First of all, thank you for this module :-).

But I have one issue. If I apply a relation filter, soft delete condition is ignored.
https://github.com/lekoala/silverstripe-softdelete/blob/047694a334425065a765c5c55387f6a8c45f44f3/code/SoftDeletable.php#L107

e.g.
`MyObject::get()->filter('Relation.ID', 3)->count();`

**Comment by lekoala** [comment]
@rasstislav ok interesting! i think i'd rather avoid using filtersOnID entirely if that's the case and check for Table.ID presence to trigger this.
I've pushed on master an update can you check if that works for you?

**Comment by rasstislav** [comment]
> @rasstislav ok interesting! i think i'd rather avoid using filtersOnID entirely if that's the case and check for Table.ID presence to trigger this. I've pushed on master an update can you check if that works for you?

It doesn't look bad and it works in my case :-). Thanks.
