### ISSUE TITLE
SoftDeleteModelAdmin dataFieldByName not working for detailed implementations of $managed_models

### ISSUE THREAD

**Issue by guywatson** [lekoala/silverstripe-softdelete#9]
SoftDeleteModelAdmin.php

```
    protected function getSanistedModelClass()
    {
        return str_replace('\\', '-', $this->owner->modelClass);
    }
```
needs to use `$this->owner->modelTab` because the GridField is constructed using `modelTab` https://github.com/silverstripe/silverstripe-admin/blob/2/code/ModelAdmin.php#L286

**Comment by lekoala** [comment]
fixed 
https://github.com/lekoala/silverstripe-softdelete/releases/tag/3.0.6
